# Generated by Django 3.1.4 on 2020-12-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_auto_20201206_0248'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades Empleados',
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['-firts_name', 'last_name'], 'verbose_name': 'Mi Empleado', 'verbose_name_plural': 'Empleados de la Empresa'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null='True', upload_to='empleado'),
            preserve_default='True',
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('firts_name', 'departamento')},
        ),
    ]
